version: '3.9'
services:
  mysql:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mariadb:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
      - MARIADB_DATABASE=go_auth_srv
  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
